
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


blazar.tokenutil.privateKey.file=classpath:jwt-signing-private.pem
blazar.tokenutil.publicKey.file=classpath:jwt-signing-public.pem
